import Head from "next/head";
import Image from "next/image";
import BannerComponent from "../components/banner";
import NavbarComponent from "../components/navbar";
import Stories from "../components/stories";

export default function Home() {
  return (
    <div className="dark:bg-black">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full px-12 bg-black">
        <NavbarComponent />
        <BannerComponent />
        <Stories />
      </div>
    </div>
  );
}
