import Head from "next/head";
import Image from "next/image";
import NavbarComponent from "./components/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-12">
        <NavbarComponent />
      </div>
    </div>
  );
}
